### ISSUE TITLE
Documentation is wrong about `bubbles`

### ISSUE THREAD

**Issue by boris-petrov** [buschtoens/ember-on-modifier#212]
The title is not *exactly* true. I believe `bubbles=false` actually does *both* `preventDefault` and `stopPropagation` so you might want to note that in the documentation so people convert correctly their old code.

**Comment by buschtoens** [comment]
AFAICT from the [`{{action}}` modifier code](https://github.com/emberjs/ember.js/blob/6ff19354e54bf89e3178fff053eb9c59dbf92d01/packages/%40ember/-internals/glimmer/lib/modifiers/action.ts#L141-L143), when setting `bubbles=true`, it only calls `stopPropagation()`.

**Comment by boris-petrov** [comment]
Yes, but it also returns `shouldBubble`, which when `false`, also prevents the default action. I'm seeing that this is happening, that's why I opened this. Only putting `(stop-propagation ...` doesn't match the behavior of `bubbles=false` from the `action` modifier.

**Comment by buschtoens** [comment]
I think you're rather seeing this:

> Events triggered through the action helper will automatically have `.preventDefault()` called on them. You do not need to do so in your event handlers. If you need to allow event propagation (to handle file inputs for example) you can supply the `preventDefault=false` option to the `{{action}}` helper.

— [Event Propagation](https://api.emberjs.com/ember/3.15/classes/Ember.Templates.helpers/methods/action?anchor=action#event-propagation)

Can you confirm?

Either way, you are right. The `ember-on-modifier` docs suggest that `preventDefault=false` ia the default, while it actually is `preventDefault=true`.

**Comment by boris-petrov** [comment]
hm, I'm even more confused now. Maybe I'm seeing this, yes.

BUT I'm absolutely sure that the built-in `on` modifier in Ember 3.15 does NOT prevent default by default. I have to explicitly use your `prevent-default` helper in a bunch of places. Is that a bug in `on` or in the documentation you're referring to? Actually having a default `preventDefault=true` would be perfect for the `on` modifier but it's not so...

**Comment by buschtoens** [comment]
Note that the docs I linked are for _`{{action}}`_. 😊 

By default, `{{action}}` uses `preventDefault=true` and calls `event.preventDefault()`. You have to explicitly opt-out by setting `preventDefault=false`.

`{{on}}` (neither `ember-on-modifier` nor the Ember Core implementation) do this. You need to either use the `(prevent-default)` helper or call `event.preventDefault()` yourself. ☺️

**Comment by boris-petrov** [comment]
Ah, OK, from your previous post I understood that `ember-on-modifier` prevents default by default (how else should I understand your last sentence?! :smile:).

So yes, the only thing you have to fix is the README here to note that converting from the `action` modifier also needs `prevent-default` to have the same behavior as before.

**Comment by buschtoens** [comment]
> Either way, you are right. The `ember-on-modifier` docs suggest that `preventDefault=false` is the default ***behaviour of `{{action}}`***, while it actually is `preventDefault=true`.

In inserted a bit to make more clear, what I was referring to. 😅 

Sorry for all this confusion and thanks for reporting this!
