### ISSUE TITLE
Deprecation warning after installing this package (implicit-modifier-manager-capabilities)

### ISSUE THREAD

**Issue by joshuaswift** [buschtoens/ember-on-modifier#275]
Hi! We recently installed this package and since installing get the following deprecation warning anytime the polyfill is used:

`Custom modifier managers must define their capabilities using the capabilities() helper function [deprecation id: implicit-modifier-manager-capabilities]`

We're running version `2.18.2` of ember-cli.

Let me know if you need any more info 😄

**Comment by buschtoens** [comment]
What version of `ember-source` are you using? :)

btw, even if you're somehow locked to an old version of `ember-source`, you can still (and should) update `ember-cli`.

**Comment by joshuaswift** [comment]
`ember-source` is at `2.18.2` as well, and I didn't know that, thanks for the tip!

**Comment by ToMoCoop** [comment]
Any movement on this one, or does anyone else have a similar problem?

**Comment by buschtoens** [comment]
If anyone wants to fix this, basically we need to add `capabilities` to this object here:

https://github.com/buschtoens/ember-on-modifier/blob/8b62c9361b81d12575657973c995ed7ab64176fe/addon/modifiers/on.js#L82-L83

Like done here for a class: https://github.com/sukima/ember-class-based-modifier/pull/13/files#diff-cdfd8b429e60cfa85ed4bb76246b95bdR12

**Comment by ToMoCoop** [comment]
Thanks for this, we will take a look and hopefully contribute.

**Comment by rwjblue** [comment]
Hmm, if you are using ember-source@2.18 (you really should update, this is quite an old version and will not even receive security fixes at this point) why would you _also_ get this deprecation? That deprecation was added in https://github.com/emberjs/ember.js/pull/18266 and is only present on ember-source@3.14 and higher. 🤔

**Comment by rwjblue** [comment]
D'oh! Answered my own question: apparently I implemented the deprecation in ember-modifier-manager-polyfill as well (in https://github.com/rwjblue/ember-modifier-manager-polyfill/pull/10). 🤦‍♂️
