### ISSUE TITLE
Ensure stability when possible.

### ISSUE THREAD

**Issue by rwjblue** [buschtoens/ember-on-modifier#44]
During the implementation of `on` upstream I noticed that the listeners were being setup and destroyed **a ton**. This is because the modifiers `updateModifier` hook is called whenever the arguments may have been changed, which in the case of `{{on 'some-string' this.whatever}}` means that any time _`this`_ is updated we rerender. In the upstream implementation I do some extra backbending to ensure that we only call `removeEventListener`/`addEventListener` in updateModifier when absolutely required.

I think the following is a rough checklist to accomplish the stability we want for this as a polyfill:

* Add a small snippet to track counts of add/remove

```js
let adds = 0;
let removes = 0;
export function counts() { 
  return { adds, removes };
}

function setupListener(...) {
  adds++;
  // ...snip...
}

function destroyListener(...) {
  removes++;
  // ...snip...
}
```

* Add a helpful `assert.counts` to the assert object:

```js
// tests/test-helper.js
import { counts } from 'ember-on-modifier/modifiers/on';

QUnit.testStart(function() {
  this._startingCounts = counts();
});

QUnit.assert.counts = function(expected) {
  let current = counts();

  this.assert.deepEqual(
    current,
    {
      adds: expected.adds + this._startingCounts.adds,
      removes: expected.removes + this._startingCounts.removes,
    },
    `counters have incremented by ${JSON.stringify(expected)}`
  );
};
```

* Add some `assert.counts({ adds: 1, removes: 0})` style assertions to tests (will likely fail for "simple" things)
* Add in manual stability checks in `updateModifier`, specifically checking if the named arguments have _actually_ changed (e.g. doing `oldCallback !== newCallback` guards)

**Comment by rwjblue** [comment]
@buschtoens - I'm just laying out what I think needs to be done to ensure the same stability between this as a polyfill and the upstream implementation (and constantly adding/remvoing the listener on rerender is not good).  I won't have much time this week to work on this, but I'm happy to help if you have time or pick it up sometime next week if you don't have the time before then.(

**Comment by buschtoens** [comment]
This is also a bug in disguise, right? Since `once=true` wouldn't _really_ be working in this case. I'll make sure to add a regression test for that as well.

**Comment by rwjblue** [comment]
Ya, good point!
