### ISSUE TITLE
Make a "true" polyfill

### ISSUE THREAD

**Issue by rwjblue** [buschtoens/ember-on-modifier#45]
- [x] Deprecate usage of the `prevent-default` template helper
  - [x] Extract to [`ember-event-helpers`](https://github.com/buschtoens/ember-event-helpers)
  - [x] #48 Deprecate usage in `ember-on-modifier`
- [x] #50 Use `ember-cli-version-checker`'s `.forEmber()` to check if we are using >= 3.11.0-beta.1
  * if we are on 3.11+ disable treeForAddon
  * if we are on < 3.11, do normal processing

**Comment by buschtoens** [comment]
I started [`ember-event-helpers`](https://github.com/buschtoens/ember-event-helpers) and moved `(prevent-default)` over.

**Comment by buschtoens** [comment]
`(prevent-default)` is now deprecated in `v0.12.2`.

**Comment by buschtoens** [comment]
The polyfill is now inert for Ember `>=3.11.0-beta.1` in [`v0.12.3`](https://github.com/buschtoens/ember-on-modifier/releases/tag/v0.12.3).

Thanks @gmurphey for implementing this in #57. 🤗
