### ISSUE TITLE
preventDefault

### ISSUE THREAD

**Issue by buschtoens** [buschtoens/ember-on-modifier#5]
`{{action}}` supports a `preventDefault` option to automatically call `event.preventDefault()`:

```hbs
<a href="/" {{action this.someAction preventDefault=true}}>Click me</a>
```

We could either add the same option to `{{on}}`:

```hbs
<a href="/" {{on "click" this.someAction preventDefault=true}}>Click me</a>
```

Or explore alternative solutions. For instance, we could create a `prevent-default` helper:

```hbs
<a href="/" {{on "click" (prevent-default this.someAction)}}>Click me</a>
```

```hbs
<a href="/" {{on "click" this.someAction}} {{on "click" (prevent-default)}}>Click me</a>
```

Currently all named parameters are passed through to `addEventListener` as event options. Adding a `preventDefault` would mean that we introduce special handling for some options.

**Comment by buschtoens** [comment]
Exemplary `prevent-default` implementation:

```js
import { helper } from '@ember/component/helper';

export const preventDefault = ([handler]) => event => {
  event.preventDefault();
  if (handler) handler(event);
};

export default helper(preventDefault);
```

**Comment by rwjblue** [comment]
I'd vaguely prefer a wrapping helper over adding a hash argument. Either of these seem good to me:

```hbs
<a href="/" {{on "click" (prevent-default this.someAction)}}>Click me</a>
<a href="/" {{on "click" this.someAction}} {{on "click" (prevent-default)}}>Click me</a>

```

**Comment by NullVoxPopuli** [comment]
what if someone _always_ wants to prevent default?
```hbs
<a href="/" {{pdon "click" this.someAction}}>Click me</a>
```
idk

**Comment by lifeart** [comment]
`<a href="/" {{on-local "click" this.someAction}}>Click me</a>`
 -> local = preventDefault & stopPropagation

**Comment by lifeart** [comment]
```hbs
<a href="/" {{on "click" (dom-event this.someAction stop=true prevent=true)}} >Click me</a>
```

**Comment by buschtoens** [comment]
I've release `(prevent-default)` in [`v0.7.0`](https://github.com/buschtoens/ember-on-modifier/releases/tag/v0.7.0). 🚀 
Thanks everybody! 👍 

`stopPropagation` is tracked in #9. Excluding helpers from the build is tracked in #10.
