### ISSUE TITLE
Missing ember-fn-helper

### ISSUE THREAD

**Issue by musaffa** [buschtoens/ember-on-modifier#67]
Where is `ember-fn-helper` addon as mentioned in the [deprecation note](https://github.com/buschtoens/ember-on-modifier/blob/66b17c5813e28ccf96dbcbd12586dd8e8d51409a/addon/modifiers/on.js#L51)? I cannot find it in the npm registry.

**Comment by rwjblue** [comment]
Sorry about that @musaffa! I just published https://github.com/rwjblue/ember-fn-helper-polyfill/releases/tag/v1.0.0.

**Comment by buschtoens** [comment]
I made a new release, which points to the correct package name. Thanks!
